# Generated by Django 5.0.6 on 2024-07-20 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ball',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_position', models.FloatField(default=50.0)),
                ('y_position', models.FloatField(default=50.0)),
                ('x_speed', models.FloatField(default=4.0)),
                ('y_speed', models.FloatField(default=-4.0)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField(default=0)),
                ('paddle_position', models.FloatField(default=50.0)),
            ],
        ),
        migrations.CreateModel(
            name='GameState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_running', models.BooleanField(default=True)),
                ('ball', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pong.ball')),
                ('player_left', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_player', to='pong.player')),
                ('player_right', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_player', to='pong.player')),
            ],
        ),
    ]
