# Generated by Django 5.0.6 on 2024-07-21 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='canvas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, default=100),
        ),
    ]
