# Generated by Django 5.0.6 on 2024-07-23 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0002_player_canvas_player_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_moving_down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='is_moving_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='player',
            name='player_speed',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='canvas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.FloatField(blank=True, default=100.0),
        ),
    ]
