# Generated by Django 5.0.6 on 2024-08-18 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0003_player_is_moving_down_player_is_moving_up_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamestate',
            name='ball',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='player_left',
        ),
        migrations.RemoveField(
            model_name='gamestate',
            name='player_right',
        ),
        migrations.DeleteModel(
            name='Ball',
        ),
        migrations.DeleteModel(
            name='GameState',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
    ]
