services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 443:443
    depends_on:
      - web

  web:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      # - ./backend/:/usr/src/backend/
      - ./media:/backend/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./.env.dev
    ports:
      - 5050:80
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
    ports:
      - "4141:4141"
    depends_on:
      - web
  redis:
    image: "redis:alpine"
    ports:
      - "6380:6379"
  
volumes:
  postgres_data:
  pgadmin_data:
  