# Generated by Django 5.0.6 on 2024-08-03 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_user_login_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocked_users',
            field=models.ManyToManyField(blank=True, related_name='blocked_by_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
