# Generated by Django 5.0.6 on 2024-08-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_user_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='loser',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='loser_username',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='match',
            name='winner_username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
