# Generated by Django 4.2.14 on 2024-08-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
