# Generated by Django 5.0.6 on 2024-08-11 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_is_2fa_enabled_user_totp_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_2fa_enabled',
            new_name='enable_2fa',
        ),
    ]
