# Generated by Django 5.0.6 on 2024-08-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_user_totp_secret'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='enable_2fa',
            new_name='tfa_enabled',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='totp_secret',
            new_name='tfa_secret',
        ),
    ]
