# Generated by Django 5.0.6 on 2024-08-11 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_rename_enable_2fa_user_tfa_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tfa_secret',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
