# Generated by Django 5.0.6 on 2024-08-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_user_tfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_42',
            field=models.BooleanField(default=False),
        ),
    ]
